name: Quality Assurance
on: [push]

jobs:
  QA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - uses: abatilo/actions-poetry@v2

      - name: Setup a local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: poetry install

      - name: Run linting
        run: make lint-ci

      - name: Run tests
        run: make test-ci

      - if: github.ref == 'refs/heads/master'
        name: Upload coverage badge
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KEY_PUB }}" > ~/.ssh/id_ed25519.pub
          chmod 400 ~/.ssh/id_ed25519 ~/.ssh/id_ed25519.pub

          make badges-ci

          ssh-keyscan -H 139.59.215.140 >> ~/.ssh/known_hosts
          scp ./badges/coverage.svg root@139.59.215.140:/var/www/html/
